SELECT TSeq_orgname, blastp100213lineagesnew.field5,
  min(CASE WHEN "BLAST origin" like 'WDR26' THEN "TSeq_accver" END) AS WDR26,
  min(CASE WHEN "BLAST origin" like 'Armc8' THEN "TSeq_accver" END) AS Armc8,
  min(CASE WHEN "BLAST origin" like 'c17orf39' THEN "TSeq_accver" END) AS c17orf39
FROM blastp100213totalhits
left outer Join blastp100213lineagesnew on blastp100213totalhits.TSeq_orgname=blastp100213lineagesnew.'field6'
Where blastp100213totalhits.'field4' not like 'Bacteria'
AND TSeq_orgname not like 'Guillardia theta'
AND TSeq_orgname not like 'Salpingoeca rosetta'
AND TSeq_orgname not like 'Agaricus bisporus var. burnettii JB137-S8'
AND TSeq_orgname not like 'Ajellomyces capsulatus G186AR'
AND TSeq_orgname not like 'Ajellomyces capsulatus H143'
AND TSeq_orgname not like 'Ajellomyces capsulatus H88'
AND TSeq_orgname not like 'Ajellomyces dermatitidis ER-3'
AND TSeq_orgname not like 'Ashbya gossypii FDAG1'
AND TSeq_orgname not like 'Aspergillus fumigatus A1163'
AND TSeq_orgname not like 'Aspergillus niger'
AND TSeq_orgname not like 'Aspergillus niger ATCC 1015'
AND TSeq_orgname not like 'Aspergillus oryzae 3.042'
AND TSeq_orgname not like 'Botryotinia fuckeliana'
AND TSeq_orgname not like 'Candida glabrata'
AND TSeq_orgname not like 'Coccidioides posadasii str. Silveira'
AND TSeq_orgname not like 'Cryptococcus gattii'
AND TSeq_orgname not like 'Cryptococcus neoformans var. grubii'
AND TSeq_orgname not like 'Cryptococcus neoformans var. grubii H99'
AND TSeq_orgname not like 'Cryptococcus neoformans var. neoformans'
AND TSeq_orgname not like 'Cryptococcus neoformans var. neoformans B-3501A'
AND TSeq_orgname not like 'Hordeum vulgare'
AND TSeq_orgname not like 'Komagataella pastoris CBS 7435'
AND TSeq_orgname not like 'Magnaporthe oryzae P131'
AND TSeq_orgname not like 'Magnaporthe oryzae Y34'
AND TSeq_orgname not like 'Neurospora crassa'
AND TSeq_orgname not like 'Neurospora tetrasperma FGSC 2509'
AND TSeq_orgname not like 'Paracoccidioides brasiliensis Pb18'
AND TSeq_orgname not like 'Penicillium digitatum Pd1'
AND TSeq_orgname not like 'Saccharomyces cerevisiae'
AND TSeq_orgname not like 'Saccharomyces cerevisiae AWRI1631'
AND TSeq_orgname not like 'Saccharomyces cerevisiae AWRI796'
AND TSeq_orgname not like 'Saccharomyces cerevisiae CEN.PK113-7D'
AND TSeq_orgname not like 'Saccharomyces cerevisiae EC1118'
AND TSeq_orgname not like 'Saccharomyces cerevisiae FostersB'
AND TSeq_orgname not like 'Saccharomyces cerevisiae FostersO'
AND TSeq_orgname not like 'Saccharomyces cerevisiae JAY291'
AND TSeq_orgname not like 'Saccharomyces cerevisiae Kyokai no. 7'
AND TSeq_orgname not like 'Saccharomyces cerevisiae Lalvin QA23'
AND TSeq_orgname not like 'Saccharomyces cerevisiae RM11-1a'
AND TSeq_orgname not like 'Saccharomyces cerevisiae VL3'
AND TSeq_orgname not like 'Saccharomyces cerevisiae Vin13'
AND TSeq_orgname not like 'Saccharomyces cerevisiae YJM789'
AND TSeq_orgname not like 'Saccharomyces cerevisiae x Saccharomyces kudriavzevii VIN7'
AND TSeq_orgname not like 'Saccharomyces kudriavzevii IFO 1802'
AND TSeq_orgname not like 'Serpula lacrymans var. lacrymans S7.9'
AND TSeq_orgname not like 'Toxoplasma gondii GT1'
AND TSeq_orgname not like 'Toxoplasma gondii VEG'
AND TSeq_orgname not like 'Trichosporon asahii var. asahii CBS 8904'
group by TSeq_orgname